### ISSUE TITLE
New version Elementor removed the feature Google Sheet 

### ISSUE THREAD

**Issue by cedricDevWP** [dbjpanda/actions-pack-issue-tracker#40]
Hello,

I am using your plugin with the Google Sheet functionality but since updating WordPress + Elementor this functionality has disappeared. I cannot find the choice in the actions after sending...

![Capture d’écran 2020-08-27 à 08 55 03](https://user-images.githubusercontent.com/12508260/91407816-17532800-e843-11ea-92e6-7a7c980ffb7a.png)

**Comment by cedricDevWP** [comment]
Finally it seems that the problem comes from updating your "actions-pack" extension which makes this feature unusable.

I just updated on a preprod environment:

1) WordPress update => Feature present

2) Elementor & Elementor Pro Update => Feature Present

3) Update Actions Pack => Functionality disappeared and in addition I have the following error after the update :

![Capture d’écran 2020-08-27 à 09 17 02](https://user-images.githubusercontent.com/12508260/91409955-78302f80-e846-11ea-9352-0af4ea20dac6.png)

**Comment by dbjpanda** [comment]
Hi,
Simply deactivate the plugin, delete it and upload it manually using FTP or by any means. It seems the plugin is not unzipping properly in your server. 

Google Sheet does not appear because we have shifted the Google Sheet action from Bronze to Silver plan. However, don't be panic because we are upgrading our existing clients to Silver plan in Free of cost. Kindly send us an email to support@dbjpanda.me and we will revert you back with the procedure for free up-gradation.
